use ckb_cinnabar_verifier::{define_errors, CUSTOM_ERROR_START};

define_errors!(
    ScriptError,
    {
        UnknownScriptType = CUSTOM_ERROR_START,
        UnknownOperation,
        ScriptArgsUnexpected,
        TipHeaderNotSet,
        HeaderNotSet,
        WitnessOutputTypeNotSet,
        WitnessInputTypeNotSet,

        BadGameGlobalInitMode,
        BadGameGlobalIterationMode,
        BadTokenIssueMode,
        BadPveCreationMode,
        BadPveSettlementMode,
        BadRedeemMode,
        BadPvpSettlementMode,
        BadSporeLockupMode,

        BrokenGameGlobalMolecule,
        BrokenTokenIssueArgs,
        BrokenGlobalDataArgs,
        BrokenSporeDataMolecule,
        BrokenPveSessionMolecule,
        BrokenPveWitnessMolecule,
        BrokenOpStartBattleMolecule,
        BrokenOpSpellCardMolecule,
        BrokenOpSelectCardMolecule,
        BrokenGameplayCards,

        IssuerGlobalNotPaired,
        PveSessionCannotBeTyped,
        PvpSessionNotXudtTyped,
        RedeemSporeTypeNotFound,
        RedeemPeriodNotEnough,
        SporeCannotBeBurned,
        GameDataNotFound,
        GameDataUnexpected,
        GameplaySporeNotInCelldep,
        GameplaySporeClusterIdUnexpected,
        GameplaySporeDnaUnexpected,
        GameDataUnexpectedChanged,
        GameplayDataUnexpectedChanged,
        ActionPointOverflow,
        ActionPointUnexpectedChanged,
        GlobalDataNotInCelldep,
        GlobalOwnerProxyNotFound,
        InvalidTokenIssueAmount,
        CardsHashMismatch,
        CardsDnaSetMismatchFromCelldep,
        CardsDnaSetMismatchFromDefault,
    }
);
